export const RECEIVE_PENDING_TEXTS = 'RECEIVE_PENDING_TEXTS'
export const ADD_ACCEPTED_TEXT = 'ADD_ACCEPTED_TEXT'
export const ADD_REFUSED_TEXT = 'ADD_REFUSED_TEXT'
export const CHANGE_PAN_DIRECTION = 'CHANGE_PAN_DIRECTION'
